server:
  servlet:
    context-path: /travel
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_travel?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 50000

  resources:
    static-locations: classpath:/static

  # thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false



# redis
  redis:
    host: 139.198.178.72
    port: 6379
    #连接超时时间（毫秒）
    timeout: 0
    #缓存中Key过时时间-单位为s
    expire: 1800


# my batis 的配置
mybatis:
  type-aliases-package: com.zero.travel.pojo
  mapper-locations: classpath:mapper/*.xml
# 分页插件配置
pagehelper:
  helper-dialect: mysql

# 日志
logging:
  level:
    org:
      root: INFO
      mybatis.spring: DEBUG
    com.zero.travel: DEBUG

